version: '2'
services:
    boardgameapp-app:
        image: boardgameapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://boardgameapp-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=boardgameapp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    boardgameapp-mongodb:
        extends:
            file: mongodb.yml
            service: boardgameapp-mongodb
